version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16.1
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    volumes:
      - ./postgres-db:/var/lib/postgresql/postgres-db

  redis:
    container_name: redis
    image: redis:7.2.3
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: >
      --requirepass '${REDIS_PASSWORD}'
    restart: unless-stopped

  s3:
    container_name: s3
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "7000:9000"
      - "7001:9001"
    volumes:
      - ./s3-data:/usr/src/app/s3
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password

volumes:
  postgres-db:
  s3-data:
