export const oblastConstant = [
  "cherkasy-oblast",
  "chernihiv-oblast",
  "chernivtsi-oblast",
  "dnipropetrovsk-oblast",
  "donetsk -oblast",
  "ivano-frankivsk-oblast",
  "kharkiv-oblast",
  "kherson-oblast",
  "khmelnytskyi-oblast",
  "kirovohrad-oblast",
  "kyiv-oblast",
  "luhansk-oblast",
  "lviv-oblast",
  "mykolaiv-oblast",
  "odesa-oblast",
  "poltava-oblast",
  "rivne-oblast",
  "sumy-oblast",
  "ternopil-oblast",
  "vinnytsia-oblast",
  "volyn-oblast",
  "zakarpattia-oblast",
  "zaporizhzhia-oblast",
  "zhytomyr-oblast",
];
